const bra = document.getElementById("brasil")
const eua = document.getElementById("eua")

const texto = document.querySelectorAll('.texto')
let textoArr = [...texto]



function clickbra(){
    bra.style.opacity = "100%"
    eua.style.opacity = "50%"
    textoArr[0].innerHTML = "INICIO"
    textoArr[1].innerHTML = "DESENVOLVEDORES"
    textoArr[2].innerHTML = "SOBRE NÓS"
    textoArr[3].innerHTML = "PORTIFÓLIO"
    textoArr[4].innerHTML = "Uma empresa desenvolvedora de sistemas que ja está no mercado a mais de duas décadas, trazendo credibilidade e empenho em nosso trabalho."
    textoArr[5].innerHTML = "CONHEÇA MAIS"
    textoArr[6].innerHTML = "CONTRATE NOSSOS SERVIÇOS"
    textoArr[7].innerHTML = "Telefone"
    textoArr[8].innerHTML = "Local"
    textoArr[9].innerHTML = "DESENVOLVEDORES"
    textoArr[10].innerHTML = "Desenvolvedor Front-End"
    textoArr[11].innerHTML = "Desenvolvedora Back-end e Front-End"
    textoArr[12].innerHTML = "Analista, Desenvolvedor Back-End e Front-End"
    textoArr[13].innerHTML = "Analista de Banco de Dados"
    textoArr[14].innerHTML = "Design Digital"
    textoArr[15].innerHTML = "Analista de Banco de Dados"
    textoArr[16].innerHTML = "Analista, Desenvolvedor Back-End e Front-End"
    textoArr[17].innerHTML = "SOBRE NÓS"
    textoArr[18].innerHTML = "A TotCode, é uma empresa tecnológica, em prol de avanços tecnológicos e desenvolvimento de sistemas, surgiu a partir de uma equipe, no dia 19 de maio de 2000, na cidade de São Paulo, Brasil. A equipe é constituída por 7 membros, na qual tem seus ensinamentos formados na Faculdade de Tecnologia de São Paulo (FATEC-SP). Há 21 anos a TotCode vem trazendo, a nossa responsabilidade e os nossos conhecimentos para a melhor solução de seus clientes."
    textoArr[19].innerHTML = "PORTIFÓLIO"
    textoArr[20].innerHTML = "ALGUNS DE NOSSOS PROJETOS ACIMA"
    textoArr[21].innerHTML = "PERGUNTAS FREQUENTES"
    textoArr[22].innerHTML = "Como entrar em contato?"
    textoArr[23].innerHTML = "Através do E-mail, telefone, redes sociais ou até mesmo em nosso estabelecimento, atendemos das 8h até 21h30."
    textoArr[24].innerHTML = "Vantagens de comprar nossos serviços"
    textoArr[25].innerHTML = "Entregamos seu sistema em até um mês, com possiveis até 3 alterações após o produto final, além de toda infraestrutura que cedemos."
    textoArr[26].innerHTML = "O que é um sistema ?"
    textoArr[27].innerHTML = "É um software ou conjunto de softwares cuja função é administrar e gerenciar os recursos de um sistema, desde componentes de hardware e sistemas de arquivos a programas de terceiros, estabelecendo a interface entre o computador e o usuário."
    textoArr[28].innerHTML = "Qual o preço de um sistema?"
    textoArr[29].innerHTML = "Gostariamos que fosse simples fornecer uma estimativa de custo instantânea e um prazo, mas sem entender os requisitos e fatores que determinam o preço de desenvolvimento de software, é quase impossível dizer."
    textoArr[30].innerHTML = "Formas de pagamento"
    textoArr[31].innerHTML = "Aceitamos cartões de crédito (bandeiras Visa,NuBank MasterCard, Elo e American Express). Também aceitamos cartões pré-pagos com bandeiras Visa, MasterCard, Elo e American Express (utilizados na função crédito). Aceitamos também PayPal."
    textoArr[32].innerHTML = "Termos de uso - Politica de privacidade"
}

console.log()

function clickeua(){
    bra.style.opacity = "50%"
    eua.style.opacity = "100%"
    textoArr[0].innerHTML = "HOME"
    textoArr[1].innerHTML = "DEVELOPERS"
    textoArr[2].innerHTML = "ABOUT US"
    textoArr[3].innerHTML = "PORTIFOLIO"
    textoArr[4].innerHTML = "A systems development company that has been in the market for more than two decades, bringing credibility and commitment to our work."
    textoArr[5].innerHTML = "LEARN MORE"
    textoArr[6].innerHTML = "HIRE OUR SERVICES"
    textoArr[7].innerHTML = "Telephone"
    textoArr[8].innerHTML = "Local"
    textoArr[9].innerHTML = "DEVELOPERS"
    textoArr[10].innerHTML = "Front-End Developer"
    textoArr[11].innerHTML = "Analyst, Back-End and Front-End Developer"
    textoArr[12].innerHTML = "Back-End and Front-End Developer"
    textoArr[13].innerHTML = "Database Analysist"
    textoArr[14].innerHTML = "Digital Design"
    textoArr[15].innerHTML = "Database Analysist"
    textoArr[16].innerHTML = "Analyst, Back-End and Front-End Developer"
    textoArr[17].innerHTML = "ABOUT US"
    textoArr[18].innerHTML = "TotCode is a company mainly related to technological advances and systems development. It emerged from a team in May 2000, in São Paulo. The team consists of 7 members, formed by FATEC-SP. For 21 years, TotCode has been bringing as its main responsibility the best solution for its customers, based on the knowledge acquired in all these years with the company. "
    textoArr[19].innerHTML = "PORTIFOLIO"
    textoArr[20].innerHTML = "SOME OF OUR PROJECTS ABOVE"
    textoArr[21].innerHTML = "COMMON QUESTIONS"
    textoArr[22].innerHTML = "How to contact us?"
    textoArr[23].innerHTML = "For E-mail, telphone, social medias or even on our stablisment, we attend from 8am to 9pm"
    textoArr[24].innerHTML = "Advantages of buying our services"
    textoArr[25].innerHTML = "We deliver your system in up to one month, with possible up to 3 changes after the final product, in addition to all the infrastructure we provide."
    textoArr[26].innerHTML = "What is software ?"
    textoArr[27].innerHTML = "It is software or a set of software whose function is to administer and manage the resources of a system, from hardware components and file systems to third-party programs, establishing the interface between the computer and the user."
    textoArr[28].innerHTML = "What is the price of a system?"
    textoArr[29].innerHTML = "We would like it to be simple to provide an instant cost estimate and a timeframe, but without understanding the requirements and factors that determine the price of software development, it is almost impossible to say."
    textoArr[30].innerHTML = "Payment methods"
    textoArr[31].innerHTML = "We accept credit cards (Visa, NuBank MasterCard, Elo and American Express). We also accept prepaid cards with Visa, MasterCard, Elo and American Express (used in the credit function). We also accept PayPal. "
    textoArr[32].innerHTML = "Use therms - privay politic"
}

